version: "3.8"
services:
  php:
    container_name: php_${PROJECT_NAME}
    image: ufotech/php:8.4-fpm
    working_dir: ${WORKDIR}
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./:${WORKDIR}

